name: Node Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./capstone_project/hello-world/
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/ s
    steps:
    - uses: actions/checkout@v2
    
    - run: pwd
      working-directory: ${{env.working-directory}}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        working-directory: ${{env.working-directory}}
    - run: npm ci |
          npm run build --if-present
          npm test
      working-directory: ${{env.working-directory}}