name: Node project
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    env:
      working-directory: ./capstone_project/hello-world/
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    
    - run: npm install
    - run: npm run test


