name: Node project
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    env:
      working-directory: ./capstone_project/hello-world/
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      env:
        CI: true
    - run: npm install
    - run: npm run test


