name: Node Project
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./capstone_project/hello-world
jobs:
  tests:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./capstone_project/hello-world
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        
        with:
          node-version: 16.x
          working-directory: ${{env.working-directory}}

      # Install dependencies21231234
      - run: npm install
        working-directory: ${{env.working-directory}}

      # Run tests
      - run: npm test
        working-directory: ${{env.working-directory}}