name: Node Project
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./capstone_project/hello-world
jobs:
  tests:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./capstone_project/hello-world
    steps:

      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        
        with:
          node-version: 16.x
      
      - run: npm ci

      - run: npm test
      - run: docker build . -t node-project
      - run: docker image ls
        